apiVersion: apps/v1
kind: Deployment
metadata:
  name: digian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digian
  template:
    metadata:
      labels:
        app: digian
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
